# Generated by Django 5.2.1 on 2025-09-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interestrate_loantype_userprofile_aadhar_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAmountSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab_name', models.CharField(help_text='e.g., Small, Medium, Large', max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Minimum amount for this slab', max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Maximum amount for this slab', max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Description of this amount slab')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_slabs', to='app.loantype')),
            ],
            options={
                'ordering': ['min_amount'],
                'unique_together': {('loan_type', 'slab_name')},
            },
        ),
        migrations.CreateModel(
            name='EMIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('tenure_months', models.IntegerField(help_text='Loan tenure in months')),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_repayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_configurations', to='app.interestrate')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_configurations', to='app.loantype')),
                ('amount_slab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emi_configurations', to='app.loanamountslab')),
            ],
            options={
                'ordering': ['loan_type', 'tenure_months'],
                'unique_together': {('loan_type', 'amount_slab', 'interest_rate', 'tenure_months', 'frequency')},
            },
        ),
    ]
